src/Bundles/msalsas/voting-bundle/Entity/Vote/AbstractVote.php
<?php

/*
 * This file is part of the MsalsasVotingBundle package.
 *
 * (c) Manolo Salsas
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Msalsas\VotingBundle\Entity\Vote;


use Symfony\Component\Security\Core\User\UserInterface;

abstract class AbstractVote
{
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var UserInterface|null|string
     */
    protected $user = null;

    /**
     * @var integer
     */
    protected $referenceArticle;

    /**
     * @var integer
     */
    protected $referenceComment;




    /**
     * @var string
     */
    protected $userIP;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id)
    {
        $this->id = $id;
    }

    /**
     * @return string|UserInterface
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param string|UserInterface $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     *
     */
    public function getReferenceArticle()
    {
        return $this->referenceArticle;
    }

    /**
     * @param  $referenceArticle
     */
    public function setReferenceArticle( $referenceArticle)
    {
        $this->referenceArticle = $referenceArticle;

    }

    /**
     * @return int
     */
    public function getReferenceComment(): int
    {
        return $this->referenceComment;
    }

    /**
     * @param  $referenceComment
     */
    public function setReferenceComment($referenceComment)
    {
        $this->referenceComment = $referenceComment;
    }

    /**
     * @return string|null
     */
    public function getUserIP(): string
    {
        return $this->userIP;
    }

    /**
     * @param string|null $userIP
     */
    public function setUserIP(string $userIP = null)
    {
        $this->userIP = $userIP;
    }

    public function isPositive()
    {
        if (get_class($this) === 'Msalsas\VotingBundle\Entity\VotePositive') {
            return true;
        }

        return false;
    }
}

src/Bundles/msalsas/voting-bundle/Resources/views/msalsas_voting_widget.html.twig
{# This file is part of the MsalsasVotingBundle package.

(c) Manolo Salsas

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code. #}

{% macro shakeIt(id,isComment) %}
    {% if isComment %}
        {% set votes = msalsas_voting_voter.positiveVotesComment(id) %}
        {% set userVote = msalsas_voting_voter.userVoteComment(id) %}
        {% set published = msalsas_voting_voter.publishedComment(id) %}

    {% else %}
        {% set votes = msalsas_voting_voter.positiveVotes(id) %}
        {% set userVote = msalsas_voting_voter.userVote(id) %}
        {% set published = msalsas_voting_voter.published(id) %}
    {% endif %}

{#    <div class="msalsas-voting-widget-wrapper">
        <div class="msalsas-voting-widget">
            <div class="msalsas-voting-shakes{% if published %} published{% endif %}">
                <p id="msalsas-voting-shakes-{{ id }}">{{ votes|default(0) }}</p> <i class="fa fa-heart {% if userVote %} --liked {% endif %}"></i>


            </div>
            <div class="msalsas-voting-shake-it{% if userVote %} --liked {% endif %}"
                 id="msalsas-voting-a-shake-{{ id }}"
                 data-id="{{ id }}"
                 data-shakentext="{{ 'msalsas_voting.shaken'|trans }}"
                    {% if isComment %}
                 data-comment="true"
                 data-url="{{ path('positive_vote_comment', {id: id, _locale: app.request.locale}) }}">
                {% else %}
                    data-url="{{ path('positive_vote', {id: id, _locale: app.request.locale}) }}">
                {% endif %}



                {% if not userVote %}
                    <a  href="javascript:void(0)">{{ 'msalsas_voting.shake_it'|trans }}</a>
                {% elseif userVote.positive %}
                    <span class="liked" id="msalsas-voting-a-positive-{{ id }}">{{ 'msalsas_voting.shaken'|trans }}</span>


                {% else %}
                    <span class="dislked" id="msalsas-voting-a-negative-{{ id }}">{{ userVote.reason|trans }}</span>
                {% endif %}
            </div>

            #}{#  <div class="msalsas-voting-clicks{% if published %} published{% endif %}">
                  {% if clicks %}
                      {{ 'msalsas_voting.clicks'|transchoice(clicks) }}
                  {% else %}
                      &nbsp;
                  {% endif %}
              </div>#}{#
        </div>
    </div>#}

    <div class="msalsas-voting-widget-wrapper">
        <div class="msalsas-voting-widget">

            <div class="msalsas-voting-shake-it{% if userVote %} --liked {% endif %}"
                 id="msalsas-voting-a-shake-{{ id }}"
                 data-id="{{ id }}"
                 data-shakentext="{{ 'msalsas_voting.shaken'|trans }}"
                    {% if isComment %}
                        data-comment="true"
                        data-url="{{ path('positive_vote_comment', {id: id, _locale: app.request.locale}) }}">
                    {% else %}
                        data-url="{{ path('positive_vote', {id: id, _locale: app.request.locale}) }}">
                    {% endif %}



                {% if not userVote %}

                    <span class="c-btn c-btn--like">
                        <p class="c-btn__number" id="like__number-{{ id }}">{{ votes|default(0) }}</p>
                        <svg  width="20" height="20" viewBox="0 0 20 20">
                        <defs>
                            <rect id="a" rx="10" />
                        </defs>
                        <g fill="none" fillRule="evenodd">
                            <rect width="19.311824" height="19.311824" x=".344088" y=".344088" stroke="#D8D8D8" strokeWidth="1" rx="9.655912" />
                            <path fill="currentColor"  fillRule="nonzero" d="M10 8.08272067c-1.04933333-1.80066666-4-1.275-4 .98133334 0 1.5536667 1.857 3.1423333 4 5.2693333 2.1433333-2.127 4-3.7156666 4-5.2693333 0-2.264-2.9583333-2.76866663-4-.9813333z" />
                        </g>
                    </svg>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                    </span>


                {% elseif userVote.positive %}
                    <span class="c-btn c-btn--like c-btn--marked" >
                        <p class="c-btn__number"  id="like__number-{{ id }}">{{ votes|default(0) }}</p>
                        <svg  width="20" height="20" viewBox="0 0 20 20">
                        <defs>
                            <rect id="a" rx="10" />
                        </defs>
                        <g fill="none" fillRule="evenodd">
                            <rect width="19.311824" height="19.311824" x=".344088" y=".344088" stroke="#D8D8D8" strokeWidth="1" rx="9.655912" />
                            <path fill="currentColor"  fillRule="nonzero" d="M10 8.08272067c-1.04933333-1.80066666-4-1.275-4 .98133334 0 1.5536667 1.857 3.1423333 4 5.2693333 2.1433333-2.127 4-3.7156666 4-5.2693333 0-2.264-2.9583333-2.76866663-4-.9813333z" />
                        </g>
                    </svg>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                        <div class="c-spark"></div>
                    </span>

                {% else %}
                    <span class="dislked" id="msalsas-voting-a-negative-{{ id }}">{{ userVote.reason|trans }}</span>
                {% endif %}
            </div>

          {#  <div class="msalsas-voting-clicks{% if published %} published{% endif %}">
                {% if clicks %}
                    {{ 'msalsas_voting.clicks'|transchoice(clicks) }}
                {% else %}
                    &nbsp;
                {% endif %}
            </div>#}
        </div>
    </div>


{% endmacro shakeIt %}

{% macro bottomBar(id) %}
    {% set votes = msalsas_voting_voter.positiveVotes(id) %}
    {% set anonymousVotes = msalsas_voting_voter.anonymousVotes(id) %}
    {% set userPositiveVotes = msalsas_voting_voter.userPositiveVotes(id) %}
    {% set negativeVotes = msalsas_voting_voter.negativeVotes(id) %}
    {% set userVote = msalsas_voting_voter.userVote(id) %}
    {% set negativeReasons = msalsas_voting_voter.negativeReasons() %}
    <div class="msalsas-voting-bottom-bar-wrapper">
        <div class="msalsas-voting-bottom-bar">
            <span class="msalsas-voting-bottom-bar-votes-up" data-toggle="tooltip" data-placement="top" title="{{ 'msalsas_voting.positive_votes'|trans }}"><i class="fa fa-arrow-circle-up"></i> <strong><span id="msalsas-voting-bottom-bar-votes-up-{{ id }}" >{{ userPositiveVotes|default(0) }}</span></strong></span>
            <span class="msalsas-voting-bottom-bar-votes-anonymous" data-toggle="tooltip" data-placement="top" title="{{ 'msalsas_voting.anonymous_votes'|trans }}"><i class="fa fa-user-secret"></i> <strong><span id="msalsas-voting-bottom-bar-votes-anonymous-{{ id }}" >{{ anonymousVotes|default(0) }}</span></strong></span>
            <span class="msalsas-voting-bottom-bar-votes-down" data-toggle="tooltip" data-placement="top" title="{{ 'msalsas_voting.negative_votes'|trans }}"><i class="fa fa-arrow-circle-down"></i> <strong><span id="msalsas-voting-bottom-bar-votes-down-{{ id }}">{{ negativeVotes|default(0) }}</span></strong></span>

            {% if not userVote and msalsas_voting_voter.userCanVoteNegative(id) %}
                <form action=""
                      id="msalsas-voting-problem-{{ id }}"
                      data-url="{{ path('negative_vote', {id: id, _locale: app.request.locale}) }}"
                      data-id="{{ id }}"
                >
                    <select name="ratings">
                        <option value="0" selected="selected">{{ 'msalsas_voting.problem'|trans }}</option>
                        {% for value in negativeReasons %}
                            <option value="{{ value }}">{{ value|trans }}</option>
                        {% endfor %}
                    </select>
                </form>
            {% endif %}
        </div>
    </div>
{% endmacro bottomBar %}

{% macro shakeItModal() %}
    <div id="msalsas-modal">
        <div class="msalsas-modal-content">
            <span class="msalsas-close">&times;</span>
            <p id="msalsas-modal-text">Error</p>
        </div>
    </div>
{% endmacro %}

{% macro shakeItCSS() %}
    <style>{{ source('@msalsas_voting.public/css/msalsas_voting_styles.css') }}</style>
{% endmacro shakeItCSS %}

{% macro shakeItJS() %}
    <script>{{ source('@msalsas_voting.public/js/msalsas_voting_shakeIt.js') }}</script>
    <script>{{ source('@msalsas_voting.public/js/msalsas_voting_bottomBar.js') }}</script>
{% endmacro shakeItJS %}

src/Bundles/msalsas/voting-bundle/Resources/views/msalsas_voting_widget_custom.html.twig
{# This file is part of the MsalsasVotingBundle package.

(c) Manolo Salsas

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code. #}

{% macro shakeIt(id,isComment) %}
    {% if isComment %}
        {% set votes = msalsas_voting_voter.positiveVotesComment(id) %}
        {% set userVote = msalsas_voting_voter.userVoteComment(id) %}
        {% set published = msalsas_voting_voter.publishedComment(id) %}

    {% else %}
        {% set votes = msalsas_voting_voter.positiveVotes(id) %}
        {% set userVote = msalsas_voting_voter.userVote(id) %}
        {% set published = msalsas_voting_voter.published(id) %}
    {% endif %}



    <div class="msalsas-voting-widget-wrapper--comment">
            <div class="msalsas-voting-widget">
                <div class="msalsas-voting-shakes{% if published %} published{% endif %}">
                    <a id="msalsas-voting-shakes-{{ id }}">{{ votes|default(0) }}</a>
                </div>
                <div class="msalsas-voting-shake-it"
                     id="msalsas-voting-a-shake-{{ id }}"
                     data-id="{{ id }}"
                     data-shakentext="{{ 'msalsas_voting.shaken'|trans }}"
                    <{% if isComment %}
                        data-comment="true"
                        data-url="{{ path('positive_vote_comment', {id: id, _locale: app.request.locale}) }}">
                    {% else %}
                        data-url="{{ path('positive_vote', {id: id, _locale: app.request.locale}) }}">
                    {% endif %}
                    {% if not userVote %}
                        <a class="msalsas-voting-shake-it-a"  href="javascript:void(0)"><i class="far fa-heart"></i></a>
                    {% elseif userVote.positive %}
                        <span class="msalsas-voting-shake-it-a" id="msalsas-voting-a-positive-{{ id }}"><i class="fa fa-heart"></i></span>
                    {% else %}
                        <span class="msalsas-voting-shake-it-a" id="msalsas-voting-a-negative-{{ id }}"><i class="fa fa-heart"></i></span>
                    {% endif %}
                </div>
              {#  <div class="msalsas-voting-clicks{% if published %} published{% endif %}">
                    {% if clicks %}
                        {{ 'msalsas_voting.clicks'|transchoice(clicks) }}
                    {% else %}
                        &nbsp;
                    {% endif %}
                </div>#}
            </div>
        </a>
    </div>
{% endmacro shakeIt %}

{% macro bottomBar(id) %}
    {% set votes = msalsas_voting_voter.positiveVotes(id) %}
    {% set anonymousVotes = msalsas_voting_voter.anonymousVotes(id) %}
    {% set userPositiveVotes = msalsas_voting_voter.userPositiveVotes(id) %}
    {% set negativeVotes = msalsas_voting_voter.negativeVotes(id) %}
    {% set userVote = msalsas_voting_voter.userVote(id) %}
    {% set negativeReasons = msalsas_voting_voter.negativeReasons() %}
    <div class="msalsas-voting-bottom-bar-wrapper">
        <div class="msalsas-voting-bottom-bar">
            <span class="msalsas-voting-bottom-bar-votes-up" data-toggle="tooltip" data-placement="top" title="{{ 'msalsas_voting.positive_votes'|trans }}"><i class="fa fa-arrow-circle-up"></i> <strong><span id="msalsas-voting-bottom-bar-votes-up-{{ id }}" >{{ userPositiveVotes|default(0) }}</span></strong></span>
            <span class="msalsas-voting-bottom-bar-votes-anonymous" data-toggle="tooltip" data-placement="top" title="{{ 'msalsas_voting.anonymous_votes'|trans }}"><i class="fa fa-user-secret"></i> <strong><span id="msalsas-voting-bottom-bar-votes-anonymous-{{ id }}" >{{ anonymousVotes|default(0) }}</span></strong></span>
            <span class="msalsas-voting-bottom-bar-votes-down" data-toggle="tooltip" data-placement="top" title="{{ 'msalsas_voting.negative_votes'|trans }}"><i class="fa fa-arrow-circle-down"></i> <strong><span id="msalsas-voting-bottom-bar-votes-down-{{ id }}">{{ negativeVotes|default(0) }}</span></strong></span>

            {% if not userVote and msalsas_voting_voter.userCanVoteNegative(id) %}
                <form action=""
                      id="msalsas-voting-problem-{{ id }}"
                      data-url="{{ path('negative_vote', {id: id, _locale: app.request.locale}) }}"
                      data-id="{{ id }}"
                >
                    <select name="ratings">
                        <option value="0" selected="selected">{{ 'msalsas_voting.problem'|trans }}</option>
                        {% for value in negativeReasons %}
                            <option value="{{ value }}">{{ value|trans }}</option>
                        {% endfor %}
                    </select>
                </form>
            {% endif %}
        </div>
    </div>
{% endmacro bottomBar %}

{% macro shakeItModal() %}
    <div id="msalsas-modal">
        <div class="msalsas-modal-content">
            <span class="msalsas-close">&times;</span>
            <p id="msalsas-modal-text">Error</p>
        </div>
    </div>
{% endmacro %}

{% macro shakeItCSS() %}
    <style>{{ source('@msalsas_voting.public/css/msalsas_voting_styles.css') }}</style>
{% endmacro shakeItCSS %}

{% macro shakeItJS() %}
    <script>{{ source('@msalsas_voting.public/js/msalsas_voting_shakeIt.js') }}</script>
    <script>{{ source('@msalsas_voting.public/js/msalsas_voting_bottomBar.js') }}</script>
{% endmacro shakeItJS %}